### ISSUE TITLE
Can’t compile: map_util.h not found

### ISSUE THREAD

**Issue by johannessen** [majensen/libneo4j-client#2]
Running `make clean check` on version https://github.com/majensen/libneo4j-client/commit/44697708969a03c1f2508d606ec0a9ee05b31b39 results in the following error message:

    connection.c:33:10: fatal error: 'map_util.h' file not found

**Comment by majensen** [comment]
That was cruft - try what's in master now

**Comment by johannessen** [comment]
Thanks. Build succeeds now, gonna test timeout etc. tomorrow (hopefully).
