### ISSUE TITLE
Current dbname not reported correctly

### ISSUE THREAD

**Issue by johannessen** [majensen/libneo4j-client#3]
Running 1b2a58aff051d424fd216784a0cb9404db94a7fc:

````
neo4j> :status
Connected to 'neo4j://neo4j@localhost:7687' (insecure) [Neo4j/4.2.1]
neo4j> :dbname system
db set
neo4j> :dbname
````

### Expected
    current db is 'system'

### Actual
    current db is 'e'

Reproducibility: **Sometimes.** I’ve also seen the db name being reported as `\` or the empty string. Sometimes, the correct name is reported. Repeated invocations of `:dbname` may yield identical or different results. A memory corruption issue…?

**Comment by majensen** [comment]
Yes - I had this issue too, but I guess I didn't nail it. Will look
