### ISSUE TITLE
Switch to system database not successful

### ISSUE THREAD

**Issue by johannessen** [majensen/libneo4j-client#4]
Running 1b2a58aff051d424fd216784a0cb9404db94a7fc:

````
neo4j> :status
Connected to 'neo4j://neo4j@localhost:7687' (insecure) [Neo4j/4.2.1]
neo4j> :dbname system
db set
neo4j> SHOW DEFAULT DATABASE;
````

### Expected

````
"name","address","role","requestedStatus","currentStatus","error"
"neo4j","localhost:7687","standalone","online","online",""
````

### Actual

    <interactive>:0:0: error: Database does not exist. Database name: '

Come to think of it: Might this be the same issue as #3?

**Comment by majensen** [comment]
Should be fixed at 28f5ff1cc5477d616f69cdd92237fd5ad5ff9ccc
