### ISSUE TITLE
Timeout should be specified in seconds, not milliseconds

### ISSUE THREAD

**Issue by johannessen** [majensen/libneo4j-client#6]
Okay, so this may be a matter of opinion … mine is that sub-second differences in the timeout’s duration are insignificant and surprising to users. I _have_ read the help page, and yet I’ve multiple times caught myself having typed stuff like `:begin 10`, intending for the timeout to be 10 s rather than 10 ms.

As Bolt does require milliseconds, libneo4j-client should IMHO simply ×1000 any timeout given by the user.

**Comment by majensen** [comment]
Fixed in 28f5ff1cc5477d616f69cdd92237fd5ad5ff9ccc
