### ISSUE TITLE
Timeout error handling

### ISSUE THREAD

**Issue by johannessen** [majensen/libneo4j-client#7]
Running 1b2a58aff051d424fd216784a0cb9404db94a7fc:

````
neo4j> :status
Connected to 'neo4j://neo4j@localhost:7687' (insecure) [Neo4j/4.2.1]
neo4j> :begin 1
neo4j> RETURN true AS `tx open`;
<interactive>:1:1: error: Failed to run statement: Undefined error: 0
neo4j> :begin -1
<interactive>:1:1: error: A transaction is already open
neo4j> :rollback
<interactive>:1:1: error: Transaction timed out
````

### Expected

- For `RETURN`: an error message that mentions the tx having timed out rather than just “undefined”.
- For `:begin -1`: success, I think? After all, the tx was already closed due to the timeout.
- For `:rollback`: success, definitely. After all, we were _just_ informed that a “transaction is already open”, so rollback ought to be possible.

(Full disclosure: I’m having some trouble with Neo4j::Driver regarding tx status as well. Still working on getting that quite right.)

**Comment by majensen** [comment]
(yeah - I think the server should provide a means for checking tx status, rather than we clients having to guess)

ps. In fact, there should be a bolt call that provides the current state of the server per https://7687.org/bolt/bolt-protocol-server-state-specification-4.html !

**Comment by majensen** [comment]
I _think_ 3bec0ff2306f4d282d36e1a036f828e882dc7426 fixed this.

**Comment by johannessen** [comment]
From _just_ reading the spec, I think it is detailed enough for the Bolt client to reliably determine server state without too much guesswork.

“My” problem is how to get at that info from Perl. I think documentation should be added explaining which [client errors](https://github.com/majensen/libneo4j-client/blob/master/lib/src/error_handling.c) may not necessarily imply a tx rollback. In like 99.9 % of cases, a client error does mean that an active tx is rendered unusable, but it seems some rare exceptions may exist.

It’s on my list of things to look into. Some time.

**Comment by johannessen** [comment]
As of 7bd6dfd7f948bf390a0f17d00de4f82014405b58, the error message for `RETURN` (statement run on timed out tx) still doesn’t mention the timeout, but I think it should. `Undefined error: 0` just isn’t helpful. I’d suggest you reopen this issue.

The subsequent `:begin -1` and `:rollback` do work as expected now.
